import {
  VscodeOriginalIcon,
  AndroidOriginalIcon,
  ReactOriginalIcon,
  DartOriginalIcon,
  FlutterOriginalIcon,
  AtomOriginalIcon,
  GitOriginalIcon,
  GithubOriginalIcon,
  BitbucketOriginalIcon,
  VuejsOriginalIcon,
  ExpressOriginalIcon,
  CoffeescriptOriginalIcon,
  WebpackOriginalIcon,
  JavascriptOriginalIcon,
  UbuntuPlainIcon,
  NodejsOriginalIcon,
  TypescriptOriginalIcon,
  BootstrapOriginalIcon,
  NextjsOriginalIcon,
  MongodbOriginalIcon,
  MysqlOriginalIcon,
  OracleOriginalIcon,
  WordpressOriginalIcon,
  KotlinOriginalIcon,
  JavaOriginalIcon,
} from "react-devicons";

export default [
  {
    skillName: "VS Code",
    skillImage: VscodeOriginalIcon,
    skillLink: "https://code.visualstudio.com/",
  },
  {
    skillName: "Atom",
    skillImage: AtomOriginalIcon,
    skillLink: "https://atom.io/",
  },
  {
    skillName: "Dart",
    skillImage: DartOriginalIcon,
    skillLink: "https://dart.dev/",
  },
  {
    skillName: "Flutter",
    skillImage: FlutterOriginalIcon,
    skillLink: "https://flutter.dev/",
  },
  {
    skillName: "React JS",
    skillImage: ReactOriginalIcon,
    skillLink: "https://reactjs.org/",
  },
  {
    skillName: "Android",
    skillImage: AndroidOriginalIcon,
    skillLink: "https://developer.android.com/",
  },
  {
    skillName: "Vue JS",
    skillImage: VuejsOriginalIcon,
    skillLink: "https://vuejs.org/",
  },
  {
    skillName: "Git",
    skillImage: GitOriginalIcon,
    skillLink: "https://git-scm.com/",
  },
  {
    skillName: "Bit Bucket",
    skillImage: BitbucketOriginalIcon,
    skillLink: "https://bitbucket.org/",
  },
  {
    skillName: "Github",
    skillImage: GithubOriginalIcon,
    skillLink: "https://github.com/",
  },
  {
    skillName: "Java Script",
    skillImage: JavascriptOriginalIcon,
    skillLink: "https://www.javascript.com/",
  },
  {
    skillName: "Type Script",
    skillImage: TypescriptOriginalIcon,
    skillLink: "https://www.typescriptlang.org/",
  },
  {
    skillName: "Coffe Script",
    skillImage: CoffeescriptOriginalIcon,
    skillLink: "https://coffeescript.org/",
  },
  {
    skillName: "Webpack",
    skillImage: WebpackOriginalIcon,
    skillLink: "https://webpack.js.org/",
  },
  {
    skillName: "Node JS",
    skillImage: NodejsOriginalIcon,
    skillLink: "https://nodejs.org/",
  },
  {
    skillName: "Express JS",
    skillImage: ExpressOriginalIcon,
    skillLink: "https://expressjs.com/",
  },
  {
    skillName: "Ubuntu",
    skillImage: UbuntuPlainIcon,
    skillLink: "https://ubuntu.com/",
  },
  {
    skillName: "Next JS",
    skillImage: NextjsOriginalIcon,
    skillLink: "https://nextjs.org/",
  },
  {
    skillName: "Bootsrap",
    skillImage: BootstrapOriginalIcon,
    skillLink: "https://getbootstrap.com/",
  },
  {
    skillName: "Mongo DB",
    skillImage: MongodbOriginalIcon,
    skillLink: "https://www.mongodb.com/",
  },
  {
    skillName: "My SQL",
    skillImage: MysqlOriginalIcon,
    skillLink: "https://www.mysql.com/",
  },
  {
    skillName: "Oracle DB",
    skillImage: OracleOriginalIcon,
    skillLink: "https://www.oracle.com/uk/database/",
  },
  {
    skillName: "Java",
    skillImage: JavaOriginalIcon,
    skillLink: "https://www.java.com//",
  },
  {
    skillName: "Kotlin",
    skillImage: KotlinOriginalIcon,
    skillLink: "https://kotlinlang.org/",
  },
  {
    skillName: "Wordpress",
    skillImage: WordpressOriginalIcon,
    skillLink: "https://wordpress.org/",
  },
];
