import {
  VscodeOriginalIcon,
  AndroidOriginalIcon,
  ReactOriginalIcon,
  DartOriginalIcon,
  FlutterOriginalIcon,
  AtomOriginalIcon,
  GitOriginalIcon,
  GithubOriginalIcon,
  BitbucketOriginalIcon,
  VuejsOriginalIcon,
  ExpressOriginalIcon,
  WebpackOriginalIcon,
  JavascriptOriginalIcon,
  NodejsOriginalIcon,
  TypescriptOriginalIcon,
  NextjsOriginalIcon,
  MongodbOriginalIcon,
  MysqlOriginalIcon,
  WordpressOriginalIcon,
  KotlinOriginalIcon,
  JavaOriginalIcon,
  LinuxOriginalIcon,
  Windows8OriginalIcon,
  YarnOriginalIcon,
  NpmOriginalWordmarkIcon,
  TrelloPlainIcon,
  GatsbyOriginalIcon,
  PythonOriginalIcon,
} from "react-devicons";

export default [
  {
    skillName: "VS Code",
    skillImage: VscodeOriginalIcon,
    skillLink: "https://code.visualstudio.com/",
  },
  {
    skillName: "Yarn",
    skillImage: YarnOriginalIcon,
    skillLink: "https://yarnpkg.com/",
  },
  {
    skillName: "Python",
    skillImage: PythonOriginalIcon,
    skillLink: "https://www.python.org/",
  },
  {
    skillName: "Trello",
    skillImage: TrelloPlainIcon,
    skillLink: "https://trello.com/",
  },
  {
    skillName: "NPM",
    skillImage: NpmOriginalWordmarkIcon,
    skillLink: "https://www.npmjs.com/",
  },
  {
    skillName: "Atom",
    skillImage: AtomOriginalIcon,
    skillLink: "https://atom.io/",
  },
  {
    skillName: "Dart",
    skillImage: DartOriginalIcon,
    skillLink: "https://dart.dev/",
  },
  {
    skillName: "Flutter",
    skillImage: FlutterOriginalIcon,
    skillLink: "https://flutter.dev/",
  },
  {
    skillName: "React JS",
    skillImage: ReactOriginalIcon,
    skillLink: "https://reactjs.org/",
  },
  {
    skillName: "Android",
    skillImage: AndroidOriginalIcon,
    skillLink: "https://developer.android.com/",
  },
  {
    skillName: "Vue JS",
    skillImage: VuejsOriginalIcon,
    skillLink: "https://vuejs.org/",
  },
  {
    skillName: "Git",
    skillImage: GitOriginalIcon,
    skillLink: "https://git-scm.com/",
  },
  {
    skillName: "Bit Bucket",
    skillImage: BitbucketOriginalIcon,
    skillLink: "https://bitbucket.org/",
  },
  {
    skillName: "Github",
    skillImage: GithubOriginalIcon,
    skillLink: "https://github.com/",
  },
  {
    skillName: "Java Script",
    skillImage: JavascriptOriginalIcon,
    skillLink: "https://www.javascript.com/",
  },
  {
    skillName: "Type Script",
    skillImage: TypescriptOriginalIcon,
    skillLink: "https://www.typescriptlang.org/",
  },
  {
    skillName: "Webpack",
    skillImage: WebpackOriginalIcon,
    skillLink: "https://webpack.js.org/",
  },
  {
    skillName: "Node JS",
    skillImage: NodejsOriginalIcon,
    skillLink: "https://nodejs.org/",
  },
  {
    skillName: "Express JS",
    skillImage: ExpressOriginalIcon,
    skillLink: "https://expressjs.com/",
  },
  {
    skillName: "Linux",
    skillImage: LinuxOriginalIcon,
    skillLink: "https://ubuntu.com/",
  },
  {
    skillName: "Windows",
    skillImage: Windows8OriginalIcon,
    skillLink: "https://ubuntu.com/",
  },
  {
    skillName: "Next JS",
    skillImage: NextjsOriginalIcon,
    skillLink: "https://nextjs.org/",
  },
  {
    skillName: "Gatsby",
    skillImage: GatsbyOriginalIcon,
    skillLink: "https://www.gatsbyjs.com/",
  },
  {
    skillName: "Mongo DB",
    skillImage: MongodbOriginalIcon,
    skillLink: "https://www.mongodb.com/",
  },
  {
    skillName: "My SQL",
    skillImage: MysqlOriginalIcon,
    skillLink: "https://www.mysql.com/",
  },
  {
    skillName: "Java",
    skillImage: JavaOriginalIcon,
    skillLink: "https://www.java.com//",
  },
  {
    skillName: "Kotlin",
    skillImage: KotlinOriginalIcon,
    skillLink: "https://kotlinlang.org/",
  },
  {
    skillName: "Wordpress",
    skillImage: WordpressOriginalIcon,
    skillLink: "https://wordpress.org/",
  },
];
